### ISSUE TITLE
Other fields to save, can be 1-by-1:

### ISSUE THREAD

**Issue by kowalski** [TTFM-Labs/turntable#109]
profile photo / avatar (avatar url) / birthday and birth year / first name - family name /
 dj nickname / work email  address / phone / pronouns / referrer

**Comment by kowalski** [comment]
@turntablefm 

For profile photo / avatar, it should be uploadable as base64-encoded picture? It's our service that generates avatar url?

**Comment by turntablefm** [comment]
Avatar will be one of the avatars from our game

**Comment by kowalski** [comment]
@turntablefm right! of course!
but what about profile picture?

**Comment by turntablefm** [comment]
Don’t have that

**Comment by kowalski** [comment]
@turntablefm 
Hmm, so there is no profile picture? 
I only asked about profile picture because you put it on the list of fields

**Comment by turntablefm** [comment]
oh maybe that eventually; not right now
