### ISSUE TITLE
Forgot password flow ?

### ISSUE THREAD

**Issue by kowalski** [TTFM-Labs/turntable#112]

**Comment by kowalski** [comment]
@turntablefm is there a forgot password flow? 
If there is, does it work with text message or email or depends?

**Comment by turntablefm** [comment]
Yes. Password is for the email. Phone authenticates through sms pin only.

**Comment by kowalski** [comment]
> Phone authenticates through sms pin only.

@turntablefm which one do you mean by that:
- that user can log in using phone instead of password and this will send him one-time use pin
- that we simply verify phone number using pin during onboarding and later on the phone number is not used for anything meaningful (from pov of authorization)

**Comment by turntablefm** [comment]
phone number only used for authorization yes; and also friends matching with contacts upload

**Comment by kowalski** [comment]
sorry I have trouble understanding you

Should it support logging in using one-time-use pin that user receives on this phone?

**Comment by turntablefm** [comment]
Yes

**Comment by kowalski** [comment]
@mariusjagminas we don't have it yet, right? 
Are you sure you closed it correctly?

**Comment by mariusjagminas** [comment]
@kowalski yes. I moved all issues from user service to turntable, isue that you concerned about now is #243

**Comment by kowalski** [comment]
Ah, yes! Good
