### ISSUE TITLE
Add authentication in socket.io service for mobile

### ISSUE THREAD

**Issue by kowalski** [TTFM-Labs/turntable#216]
Ideally we would like to require that clients pass access token that they got from users service.
Signaling server should receive in env public key and verify the JWT token, only allowing connection if token checks out.

**Comment by kowalski** [comment]
Scratch that. The service should work without sign in.

**Comment by turntablefm** [comment]
there will be a client-level timeout where we kick people out (i guess it should be able to be efnroced at lowest level of user service too) if they don't signup/login after X (10? 2?) minutes of listening to music.

Joe

**Comment by kowalski** [comment]
@turntablefm this is something client can do I guess. 

Alternatively we could be generating anonymous user account for these new users and hold their identifier on device/in LocalStorage. This way we make may notes in database and know that a certain anonymous user has already used up their 10 minutes
