### ISSUE TITLE
Remove audius from implementation; refactor musicProvider.saga -> delete redundant getEndpoint generator

### ISSUE THREAD

**Issue by JaHajRF** [TTFM-Labs/turntable#325]

**Comment by turntablefm** [comment]
Uh I don’t want to remove Audius can we have it as a separate room type. We will want it for open source version

**Comment by JaHajRF** [comment]
got it. Im closing the issue then

**Comment by turntablefm** [comment]
Also could we make a room for them for Audius and then send it to the Audius founder so that he can play it and hear the issues himself? So he can fix them.

**Comment by JaHajRF** [comment]
I guess so, I will create the issue. I guess it is not a priority right now, or should I treat it such?

**Comment by turntablefm** [comment]
Not priority. Can do in 3 months.
